services:
  - type: web
    name: seo-traffic-booster
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
